# Generated by Django 3.0.5 on 2020-04-14 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('social_username', models.CharField(max_length=200)),
                ('access_token', models.TextField(blank=True)),
                ('social_active', models.BooleanField(default=False)),
                ('linq_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'unique_together': {('platform', 'social_username')},
            },
        ),
        migrations.CreateModel(
            name='user_medias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('media_id', models.TextField()),
                ('media_active', models.BooleanField(default=False)),
                ('social_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_socials')),
            ],
            options={
                'unique_together': {('platform', 'media_id')},
            },
        ),
    ]
