# filter_lists.py
# Contains a list of profanity to be blocked
# Contains a dictionary of replacements to minimize a string
import global_constants as gc

# The minimize and reduce message dictionary to reference for both
min_reduce_dict = dict({
# Unicode
'\u0001f602': '',
'\u2019'    : '',
# Translate to Word
'%' : ' percent '
})

# The minimize dictionary to reference first
minimize_dict_1 = dict({
'_' : ' ',
'@' : ' at ',
'+' : ' plus ',
'-' : ' minus ',
'=' : ' equal ',
'*' : ' star ',
'/' : ' divide ',
'.' : ' ',
"'" : '',
"`" : '',
# Positions
' 1st '   : ' first ',
' 2nd '   : ' second ',
' 3rd '   : ' third ',
' 4th '   : ' fourth ',
' 5th '   : ' fifth ',
' 6th '   : ' sixth ',
' 7th '   : ' seventh ',
' 8th '   : ' eighth ',
' 9th '   : ' ninth ',
' 10th '  : ' tenth ',
' 20th '  : ' twentieth ',
# Names
' chat bot '    : ' bot ',
' text bot '    : ' bot ',
' twitch bot '  : ' bot ',
# Remove
' wwwyoutubecom ' : ''
})

# The minimize dictionary to reference second
# Single word keys only
# Single word values only
minimize_dict_2 = dict({
' i '       : ' me ',
' aint '    : ' not ',
' sint '    : ' not ',
' em '      : ' them ',
' ate '     : ' eat ',
' cya '     : ' bye ',
' ym '      : ' my ',
' hes '     : ' he ',
' shes '    : ' she ',
' act '     : ' do ',
' owned '   : ' own ',
' owning '  : ' own ',
' owns '    : ' own ',
' can '     : ' able ',
' vid '     : ' video ',
' vids '    : ' video ',
' videos '  : ' video ',
' meaw '    : ' meow ',
' mmeeaaww ': ' meow ',
' freind '  : ' friend ',
' mate '    : ' friend ',
' cuz '     : ' because ',
' whys '    : ' why ',
' why that ': ' why ',
' regen '   : ' regenerate ',
' lloks '   : ' looks ',
' patner '  : ' partner ',
' worst '   : ' worse ',
' gere '    : ' here ',
' this '    : ' it ',
' yhis '    : ' it ',
' vrs '     : ' vs ',
' versus '  : ' vs ',
' ffoorr '  : ' for ',
' foor '    : ' for ',
' foorr '   : ' for ',
' forr '    : ' for ',
' yall '    : ' you ',
' y all '   : ' you ',
' you all ' : ' you ',
' yous '    : ' you ',
' yousall ' : ' you ',
' yous all ': ' you ',
' ya '      : ' you ',
' yu '      : ' you ',
' u '       : ' you ',
' ya '      : ' you ',
' your '    : ' you ',
' ur '      : ' you ',
' legs '    : ' leg ',
' arms '    : ' arm ',
' hurt '    : ' harm ',
' hurts '   : ' harm ',
' hurted '  : ' harm ',
' baned '   : ' ban ',
' banned '  : ' ban ',
' baning '  : ' ban ',
' banning ' : ' ban ',
' attaxk '  : ' attack ',
' siries '  : ' series ',
' profiles ': ' profile ',
' set ukp ' : ' setup ',
' chatt '   : ' chat ',
' chatting ': ' chat ',
' noice '   : ' nice ',
' slepp '   : ' sleep ',
' anyways ' : ' anyway ',
' giva '    : ' give ',
' thats '   : ' that ',
' dats '    : ' that ',
' goten '   : ' got ',
' gotten '  : ' got ',
' nace '    : ' nice ',
' made '    : ' make ',
' makes '   : ' make ',
' im '      : ' me am ',
' imma '    : ' me am ',
' ur '      : ' you ',
' whos '    : ' who ',
' whether ' : ' if ',
' thou '    : ' you ',
' tho '     : ' though ',
' blessrng ': ' blessing ',
' fights '  : ' fight ',
' fighter ' : ' fight ',
' fighting ': ' fight ',
' fought '  : ' fight ',
' speak '   : ' talk ',
' speack '  : ' talk ',
' speek '   : ' talk ',
' garbage ' : ' trash ',
' heath '   : ' health ',
' hp '      : ' health ',
' c mon '   : ' cmon ',
' dumb '    : ' unintelligent ',
' stupid '  : ' unintelligent ',
' music '   : ' sound ',
' sports '  : ' sport ',
' ran '     : ' run ',
' runs '    : ' run ',
' running ' : ' run ',
' hobbies ' : ' hobby ',
' hobbys '  : ' hobby ',
' whatchu ' : ' what you ',
' whqtchu ' : ' what you ',
' which '   : ' what ',
' wut '     : ' what ',
' wat '     : ' what ',
' wot '     : ' what ',
' whatchu ' : ' what ',
' knew '    : ' know ',
' knowing ' : ' know ',
' knwo '    : ' know ',
' paly '    : ' play ',
' hacked '  : ' hack ',
' hacker '  : ' hack ',
' hacking ' : ' hack ',
' hackking ': ' hack ',
' thsi '    : ' this ',
' naw '     : ' no ',
' nah '     : ' no ',
' not '     : ' no ',
' negative ': ' no ',
' don t '   : ' no ',
' dont '    : ' no ',
' never '   : ' no ',
' wont '    : ' do no ',
' doesnt '  : ' do no ',
' doin '    : ' do ',
' doing '   : ' do ',
' alright ' : ' ok ',
' allright ': ' ok ',
' drugs '   : ' drug ',
' num num ' : ' food ',
' num nums ': ' food ',
' nom '     : ' food ',
' noms '    : ' food ',
' named '   : ' called ',
' possibly ': ' maybe ',
' possibly ': ' maybe ',
' yesh '    : ' yes ',
' yeah '    : ' yes ',
' yup '     : ' yes ',
' aye '     : ' yes ',
' always '  : ' yes ',
' most '    : ' more ',
' least '   : ' less ',
' too '     : ' also ',
' as well ' : ' also ',
' sry '     : ' sorry ',
' sory '    : ' sorry ',
' wierd '   : ' weird ',
' weerd '   : ' weird ',
' a '       : ' the ',
' an '      : ' the ',
' da '      : ' the ',
' ma '      : ' my ',
' mum '     : ' mom ',
' mother '  : ' mom ',
' da '      : ' dad ',
' daddy '   : ' dad ',
' father '  : ' dad ',
' sis '     : ' sister ',
' sisters ' : ' sister ',
' bro '     : ' brother ',
' bros '    : ' brother ',
' bru '     : ' brother ',
' bruh '    : ' brother ',
' bruhh '   : ' brother ',
' brudha '  : ' brother ',
' brothers ': ' brother ',
' found '   : ' find ',
' haves '   : ' have ',
' haqe '    : ' have ',
' haqes '   : ' have ',
' possess ' : ' have ',
' has '     : ' have ',
' woman '   : ' female ',
' girl '    : ' female ',
' man '     : ' male ',
' boy '     : ' male ',
' bits '    : ' bit ',
' dollars ' : ' dollar ',
' kid '     : ' child ',
' kids '    : ' child ',
' children ': ' child ',
' babies '  : ' child ',
' infant '  : ' child ',
' infants ' : ' child ',
' toddler ' : ' child ',
' toddlers ': ' child ',
' youth '   : ' child ',
' chiocke ' : ' chicken ',
' obvious ' : ' clear ',
' clearly ' : ' clear ',
' muted '   : ' mute ',
' jail '    : ' prison ',
' eyoo '    : ' hi ',
' hai '     : ' hi ',
' heey '    : ' hi ',
' helo '    : ' hi ',
' hey '     : ' hi ',
' heya '    : ' hi ',
' heyguys ' : ' hi ',
' heylo '   : ' hi ',
' heyllo '  : ' hi ',
' wassup '  : ' hi ',
' wass up ' : ' hi ',
' whatsup ' : ' hi ',
' yo '      : ' hi ',
' yoo '     : ' hi ',
' aight '   : ' ok ',
' alright ' : ' ok ',
' genuine ' : ' true ',
' tis '     : ' this ',
' tomorrow ': ' future ',
' pls '     : ' please ',
' dieing '  : ' dying ',
' deiing '  : ' dying ',
' dyeing '  : ' dying ',
' deying '  : ' dying ',
' coumt '   : ' count ',
' vacation ': ' holiday ',
' type '    : ' kind ',
' typin '   : ' typing ',
' fallow '  : ' follow ',
' fllow '   : ' follow ',
' lnk '     : ' link ',
' x box '   : ' xbox ',
' ps1 '     : ' playstation ',
' ps2 '     : ' playstation ',
' ps3 '     : ' playstation ',
' ps4 '     : ' playstation ',
' fairies ' : ' fairy ',
' fairys '  : ' fairy ',
' faeries ' : ' fairy ',
' faery '   : ' fairy ',
' trolle '  : ' troll ',
' trolles ' : ' troll ',
' trolls '  : ' troll ',
' trollss ' : ' troll ',
' monster ' : ' troll ',
' monsters ': ' troll ',
' smoosh '  : ' squash ',
' smash '   : ' squash ',
' flying '  : ' fly ',
' flew '    : ' fly ',
' jumping ' : ' jump ',
' jumped '  : ' jump ',
' nbow '    : ' now ',
' today '   : ' now ',
' rn '      : ' now ',
' rescue '  : ' save ',
' defend '  : ' save ',
' protect ' : ' save ',
' preserve ': ' save ',
' helpful ' : ' help ',
' helped '  : ' help ',
' helping ' : ' help ',
' handy '   : ' help ',
' assist '  : ' help ',
' support ' : ' help ',
' suppoert ': ' help ',
' shortly ' : ' soon ',
' asap '    : ' soon ',
' quickly ' : ' fast ',
' quick '   : ' fast ',
' quicker ' : ' fast ',
' faster '  : ' fast ',
' fastly '  : ' fast ',
' swift '   : ' fast ',
' swiftly ' : ' fast ',
' glad '    : ' happy ',
' pleased ' : ' happy ',
' giddy '   : ' happy ',
' awesomw ' : ' good ',
' gud '     : ' good ',
' guds '    : ' good ',
' guud '    : ' good ',
' goods '   : ' good ',
' yummy '   : ' good ',
' great '   : ' good ',
' terrific ': ' good ',
' better '  : ' good ',
' best '    : ' good ',
' fine '    : ' good ',
' alright ' : ' good ',
' cool '    : ' good ',
' hourly '  : ' often ',
' daily '   : ' often ',
' weekly '  : ' often ',
' tho '     : ' though ',
' little '  : ' small ',
' scrawny ' : ' small ',
' huge '    : ' large ',
' big '     : ' large ',
' beefy '   : ' large ',
' massive ' : ' large ',
' man '     : ' human ',
' mans '    : ' human ',
' woman '   : ' human ',
' womans '  : ' human ',
' humans '  : ' human ',
' mankind ' : ' human ',
' womankind '   : ' human ',
' humankind '   : ' human ',
' robot '       : ' bot ',
' botted '      : ' bot ',
' vot '         : ' bot ',
' bot program ' : ' bot ',
' dumb bot '    : ' bot ',
' stupid bot '  : ' bot ',
' wonderful '   : ' good ',
' fantastic '   : ' good ',
' yesterday '   : ' past ',
' differently ' : ' different ',
' affirmative ' : ' yes ',
' typically '   : ' usually ',
' meaning '     : ' purpose ',
' deleted '     : ' delete ',
' deleting '    : ' delete ',
' happened '    : ' happen ',
' happening '   : ' happen ',
' sometimes '   : ' maybe ',
' some thing '  : ' something ',
' some things ' : ' something ',
' somethings '  : ' something ',
' things '      : ' thing ',
' forgot '      : ' forget ',
' forgoted '    : ' forget ',
' forgotted '   : ' forget ',
' forgotten '   : ' forget ',
' messages '    : ' message ',
' heyy '        : ' hi ',
' hio '         : ' hi ',
' wasup  '      : ' hi ',
' helloe  '     : ' hi ',
' hoi  '        : ' hi ',
' holo  '       : ' hi ',
' holoo  '      : ' hi ',
' heloo '       : ' hi ',
' hello '       : ' hi ',
' helloo '      : ' hi ',
' howdy doody ' : ' hi ',
' soo '         : ' so ',
' therefore '   : ' so ',
' certainly '   : ' yes ',
' gigantic '    : ' large ',
' gargantuan '  : ' large ',
' potatos '     : ' potato ',
' potatoes '    : ' potato ',
' tater '       : ' potato ',
' taters '      : ' potato ',
' pinapple '    : ' pineapple ',
' pineapples '  : ' pineapple ',
' immediately ' : ' soon ',
' goodnight '   : ' good night ',
' change '      : ' update ',
' changing '    : ' update ',
' changed '     : ' update ',
' updated '     : ' update ',
' updating '    : ' update ',
' improve '     : ' update ',
' improved '    : ' update ',
' improving '   : ' update ',
' commands '    : ' command ',
' commanded '   : ' command ',
' commanding '  : ' command ',
' automatic '   : ' auto ',
' automated '   : ' auto ',
' automatatic ' : ' auto ',
' watch '       : ' see ',
' watching '    : ' see ',
' watched '     : ' see ',
' headquarters ': ' hq ',
' nm '          : ' nevermind ',
' never mind '  : ' nevermind ',
' frequent '    : ' often ',
' frequently '  : ' often ',
' coment '      : ' comment ',
' commenting '  : ' comment ',
' commenting '  : ' comment ',
' overjoyed '   : ' happy ',
' ideas '       : ' thoughts ',
' domestic '    : ' home ',
' house '       : ' home ',
' indoor '      : ' inside ',
' indoors '     : ' inside ',
' fav '         : ' favorite ',
' prefer '      : ' favorite ',
' preferred '   : ' favorite ',
' cute '        : ' attractive ',
' cutie '       : ' attractive ',
' pretty '      : ' attractive ',
' beautiful '   : ' attractive ',
' butefuw '     : ' attractive ',
' adorable '    : ' attractive ',
' opressor '    : ' oppressor ',
' opressors '   : ' oppressor ',
' oppressors '  : ' oppressor ',
' opresser '    : ' oppressor ',
' opressers '   : ' oppressor ',
' oppresser '   : ' oppressor ',
' oppressers '  : ' oppressor ',
' cofuzled '    : ' confuse ',
' confused '    : ' confuse ',
' confusing '   : ' confuse ',
' confuzled '   : ' confuse ',
' questin '     : ' question ',
' questins '    : ' question ',
' questions '   : ' question ',
' responded '   : ' respond ',
' responding '  : ' respond ',
' viewers '     : ' viewer ',
' follower '    : ' viewer ',
' followers '   : ' viewer ',
' subs '        : ' viewer ',
' subscribers ' : ' viewer ',
' thx '         : ' thanks ',
' thank '       : ' thanks ',
' thank you '   : ' thanks ',
' facecam '     : ' cam ',
' face cam '    : ' cam ',
' camara '      : ' cam ',
' camera '      : ' cam ',
' microphone '  : ' mic ',
' in stream '       : ' on channel ',
' streaming '       : ' channel ',
' livestream '      : ' channel ',
' livestreamed '    : ' channel ',
' livestreaming '   : ' channel ',
' stream '          : ' channel ',
' chnnal '          : ' channel ',
# Holidays
' xmas '            : ' christmas ',
' mary christmas '  : ' merry christmas ',
' mary xmas '       : ' merry christmas ',
' ho ho ho '        : ' ',
# Animals
' beast '       : ' animal ',
' cat '         : ' animal ',
' cats '        : ' animal ',
' catt '        : ' animal ',
' catto '       : ' animal ',
' catz '        : ' animal ',
' dog '         : ' animal ',
' dogg '        : ' animal ',
' doggo '       : ' animal ',
' dogo '        : ' animal ',
' dogs '        : ' animal ',
' dogz '        : ' animal ',
' elephant '    : ' animal ',
' elephants '   : ' animal ',
' fish '        : ' animal ',
' goldfish '    : ' animal ',
' hamster '     : ' animal ',
' hamsters '    : ' animal ',
' kat '         : ' animal ',
' katt '        : ' animal ',
' kittie '      : ' animal ',
' kitty '       : ' animal ',
' kitty cat '   : ' animal ',
' kittyy '      : ' animal ',
' animal cat '  : ' animal ',
' kitten '      : ' animal ',
# Colors
' black '       : ' color ',
' blue '        : ' color ',
' brown '       : ' color ',
' gold '        : ' color ',
' gray '        : ' color ',
' green '       : ' color ',
' grey '        : ' color ',
' indigo '      : ' color ',
' light blue '  : ' color ',
' light green ' : ' color ',
' light red '   : ' color ',
' magenta '     : ' color ',
' orange '      : ' color ',
' pink '        : ' color ',
' platinum '    : ' color ',
' purple '      : ' color ',
' red '         : ' color ',
' silver '      : ' color ',
' turquoise '   : ' color ',
' violet '      : ' color ',
' white '       : ' color ',
' yellow '      : ' color ',
' colored '     : ' color ',
' coloring '    : ' color ',
' sky blue '    : ' sky color ',
# Games
' call of duty ': gc.FILTER_GAME,
' cod '         : gc.FILTER_GAME,
' dota '        : gc.FILTER_GAME,
' dota2 '       : gc.FILTER_GAME,
' forkknife '   : gc.FILTER_GAME,
' forknife '    : gc.FILTER_GAME,
' fortnite '    : gc.FILTER_GAME,
' minecraft '   : gc.FILTER_GAME,
' team fortress '   : gc.FILTER_GAME,
' team fortress 2 ' : gc.FILTER_GAME,
' tf2 '             : gc.FILTER_GAME,
# Math
'sin2x'         : ' number ',
'cos2x'         : ' number ',
'tan2x'         : ' number ',
# Foreign spellings
' dasvidaniya ' : ' bye ',
' dasvidanias ' : ' bye ',
' ahoy '        : ' hi ',
' gatto '       : ' cat ',
' hola '        : ' hi ',
' holaa '       : ' hi ',
' ola '         : ' hi ',
' olaa '        : ' hi ',
' selam '       : ' hi ',
' colour '      : ' color ',
' coloured '    : ' color ',
' colouring '   : ' color ',
' favourite '   : ' favorite ',
# Locations
' australia '       : gc.FILTER_LOCATION,
' brasil '          : gc.FILTER_LOCATION,
' brazil '          : gc.FILTER_LOCATION,
' canada '          : gc.FILTER_LOCATION,
' colombia '        : gc.FILTER_LOCATION,
' france '          : gc.FILTER_LOCATION,
' mexico '          : gc.FILTER_LOCATION,
' new zealand '     : gc.FILTER_LOCATION,
' russia '          : gc.FILTER_LOCATION,
' south america '   : gc.FILTER_LOCATION,
' sri lanka '       : gc.FILTER_LOCATION,
' united states '   : gc.FILTER_LOCATION,
# Nationalities
' american '        : gc.FILTER_NATIONALITY,
' brasilian '       : gc.FILTER_NATIONALITY,
' brazilian '       : gc.FILTER_NATIONALITY,
' australian '      : gc.FILTER_NATIONALITY,
' canadian '        : gc.FILTER_NATIONALITY,
' french '          : gc.FILTER_NATIONALITY,
' mexican '         : gc.FILTER_NATIONALITY,
' new zealander '   : gc.FILTER_NATIONALITY,
' russian '         : gc.FILTER_NATIONALITY,
' sri lankan '      : gc.FILTER_NATIONALITY,
# Emoticons
' coolcat '         : ' ',
' coolstorybob '    : ' ',
' crankthatffac '   : ' ',
' dxcat '           : ' ',
' fbblock '         : ' ',
' feelsbadman '     : ' ',
' holidaysanta '    : ' ',
' jokoevil '        : ' ',
' jokonaenae '      : ' ',
' kreygasm '        : ' ',
' malenapumpega '   : ' ',
' nmpsmile '        : ' ',
' ohmydog '         : ' ',
' pezsmile '        : ' ',
' felpssh '         : ' ',
' pixelbob '        : ' ',
' pogchamp '        : ' ',
' powerupl '        : ' ',
' powerupr '        : ' ',
' redshmm '         : ' ',
' residentsleeper ' : ' ',
' serioussloth '    : ' ',
' twitchraid '      : ' ',
' twitchunity '     : ' ',
# Social Media
' instagram '   : gc.FILTER_SOCIAL_MEDIA,
' twitter '     : gc.FILTER_SOCIAL_MEDIA,
' twich '       : gc.FILTER_SOCIAL_MEDIA,
' twitch '      : gc.FILTER_SOCIAL_MEDIA,
' youtube '     : gc.FILTER_SOCIAL_MEDIA,
' facebook '    : gc.FILTER_SOCIAL_MEDIA
})

# The minimize dictionary to reference third.
# This dictionary acts similar to dict_2, but
# the words in it depend on other words in
# dict_2 getting converted first.
minimize_dict_3 = dict({
# Removed words
' but '     : ' ',
' sort of ' : ' ',
' sorta '   : ' ',
' kinda '   : ' ',
' kind of ' : ' ',
' the hell ': ' ',
' ooo '     : ' ',
' rip '     : ' ',
' welp '    : ' ',
' iz '      : ' ',
' are '     : ' ',
' ar '      : ' ',
' r '       : ' ',
' entire '  : ' ',
' entirity ': ' ',
' entirety ': ' ',
' whole '   : ' ',
# Reduce multiple words
' i m '     : ' me am ',
' buti '    : ' me ',
' goes '    : ' go ',
' goin '    : ' go ',
' going '   : ' go ',
' doo doo ' : ' bad ',
' it it '   : ' it ',
' ive '     : ' i have ',
' ypu '     : ' you ',
' do you '  : ' you ',
' due you ' : ' you ',
' a pet '   : ' pet ',
' youll '   : ' you will ',
' ill '     : ' i will ',
' hell '    : ' he will ',
' shell '   : ' she will ',
' cmon '    : ' come on ',
' yw '      : ' you welcome ',
' how own ' : ' who own ',
' wana '    : ' want ',
' wanna '   : ' want ',
' wanted '  : ' want ',
' wanting ' : ' want ',
' a animal ': ' animal ',
' gotta '   : ' got to ',
' gonna '   : ' go to ',
' gunna '   : ' go to ',
' cant '        : ' do no ',
' cant not '    : ' do no ',
' would not '   : ' do no ',
' healthbar '   : ' health bar ',
' sofa king '   : ' so f ing ',
' we tall did ' : ' retarded ',
' we todd did ' : ' retarded ',
' we tod did '  : ' retarded ',
' speak well '  : ' talk good ',
' back story '  : ' backstory ',
' more terrible '   : ' worse ',
' animal animal '   : ' animal ',
' understand well ' : ' understand ',
' color and color ' : ' color ',
' color plus color ': ' color ',
' bye bye '         : ' bye ',
' bye bye bye '     : ' bye ',
' i am go bye '     : ' bye ',
' i am goin bye '   : ' bye ',
' i am going bye '  : ' bye ',
' me am go bye '    : ' bye ',
' me am goin bye '  : ' bye ',
' me am going bye ' : ' bye ',
# Reduce Long Filters
' ' + gc.FILTER_SOCIAL_MEDIA + ' channel '  : gc.FILTER_SOCIAL_MEDIA
})

# The minimize dictionary to reference fourth.
# If a key or value is two or more words, it
# must come after dict_2 and dict_3
# If a key should be changed whether it appears
# in the middle of a word or not, it must come
# before dict_4
minimize_dict_4 = dict({
'playz'     : 'plays',
' d '       : ' ',
' crap '    : ' ',
' actually ': ' ',
' just '    : ' ',
' imo '     : ' ',
' tbh '     : ' ',
' waht '    : ' what ',
' wtf '     : ' what ',
' tf '      : ' what ',
' wyd '     : ' what you do ',
' idk '     : ' i no know ',
' started ' : ' start ',
' starting ': ' start ',
' treatin ' : ' treat ',
' treating ': ' treat ',
' tretin '  : ' treat ',
' treting ' : ' treat ',
' its '     : ' it ',
' howr '    : ' how ',
' howre '   : ' how ',
' howve '   : ' how ',
' how able ': ' how ',
' how to '  : ' how ',
' how i '   : ' how ',
' how me '  : ' how ',
' how you ' : ' how ',
' how we '  : ' how ',
' theyre '  : ' they ',
' hows '    : ' how ',
' whatre '  : ' what ',
' whatr '   : ' what ',
' whats '   : ' what ',
' whatis '  : ' what ',
' wheres '  : ' where ',
' and the ' : ' and ',
' plus the ': ' and ',
' yoy '     : ' you ',
' youre '   : ' you ',
' did you ' : ' you ',
' ia no '   : ' is no ',
' on life ' : ' in life ',
' able i '  : ' able me ',
' can i '   : ' able me ',
' may i '   : ' able me ',
' can you '     : ' able you ',
' could you '   : ' able you ',
' may you '     : ' able you ',
' real fast '   : ' fast ',
' why is yo '   : ' why you ',
' will follow ' : ' follow ',
' respond to '  : ' answer ',
' good looking ': ' attractive ',
' food food '   : ' food ',
' human being ' : ' human ',
' my species '  : ' human ',
' homo sapiens ': ' human ',
' for sure '    : ' yes ',
' a human '     : ' human ',
' in a second ' : ' soon ',
' in a minute ' : ' soon ',
' in a bit '    : ' soon ',
' about the '   : ' about ',
' health bar '  : ' bar ',
' what this is ': ' what this ',
' home animal ' : ' animal ',
' color animal ': ' animal ',
' attractive good ' : ' good ',
' more favorite '   : ' favorite ',
' color home animal '   : ' animal ',
' hru '                     : ' how you ',
' how are you doing '       : ' how you ',
' how are you doing now '   : ' how you ',
' attractive attractive '   : ' attractive ',
' may i interest you in '   : ' want ',
' what is go on here '      : ' what this ',
' what is goin on here '   : ' what this ',
' what is going on here '   : ' what this ',
' do you like to play '     : ' do you like ',
' do you play '             : ' do you like ',
# Random number
' random number between '           : ' number between ',
' give me a number between '        : ' number between ',
' pick a number between '           : ' number between ',
' pick a random number between '    : ' number between ',
# Descriptors/Adverbs are not necessary, should be removed
' aw '      : ' ',
' awh '     : ' ',
' aww '     : ' ',
' so '      : ' ',
' soo '     : ' ',
' like '    : ' ',
' at all '  : ' ',
' of '      : ' ',
' any '     : ' ',
' very '    : ' ',
' really '  : ' ',
' please '  : ' ',
' pls '     : ' ',
' lul '     : ' ',
' lulz '    : ' ',
' lol '     : ' ',
' lolz '    : ' ',
' lolol '   : ' ',
' oml '     : ' ',
' finally ' : ' ',
' however ' : ' ',
' i guess ' : ' ',
' mofo '    : ' ',
' xd '      : ' ',
' gee '     : ' ',
' yess '    : ' yes ',
' noo '     : ' no ',
' meoww '   : ' meow ',
' meoow '   : ' meow ',
' meooww '  : ' meow ',
' meeooww ' : ' meow ',
' mmeeooww ': ' meow ',
' um '      : ' ',
' umm '     : ' ',
' yo  '     : ' ',
' yoo '     : ' ',
' really '      : ' ',
' leleellel '   : ' ',
' obviously '   : ' ',
' absolutely '  : ' ',
' extremely '   : ' ',
' seriously '   : ' ',
' by any chance '   : ' ',
' pretty please '   : ' ',
# Temporary replacements until a fix is implemented #TODO
' aha '         : ' ',
' ahaha '       : ' ',
' ahahaha '     : ' ',
' ahahahaha '   : ' ',
' ahahahahaha ' : ' ',
' ahahahahahaha '   : ' ',
' ahahahahahahaha ' : ' ',
' hehe '        : ' ',
' heehee '      : ' ',
' hehee '       : ' ',
' heehe '       : ' ',
' number number '       : ' number ',
' number number number ': ' number ',
' number number number number '         : ' number ',
' number number number number number '  : ' number ',
' number number number number number number '                                           : ' number ',
' number number number number number number number '                                    : ' number ',
' number number number number number number number number '                             : ' number ',
' number number number number number number number number number '                      : ' number ',
' number number number number number number number number number number '               : ' number ',
' number number number number number number number number number number number '        : ' number ',
' number number number number number number number number number number number number ' : ' number ',
# No comment people
'bill cosby' : ' [no-comment-person] ',
'ralph wiggum' : ' [no-comment-person] '
})

# The minimize dictionary to reference fifth.
minimize_dict_5 = dict({
' is '  : ' ',
' number number '   : ' number ',
' number am '       : ' early ',
' number pm '       : ' late ',
' l number nk '     : ' link ',
# Sensitive Topics
' lgbtq '   : ' lgbt ',
' lgbtqiia ': ' lgbt ',
' lgbtqia ' : ' lgbt '
})

# The minimize dictionary for LEET speak
minimize_dict_leet = dict({
'1'         : 'l',
'2'         : '',
'3'         : 'e',
'4'         : 'a',
'5'         : 's',
'6'         : 'b',
'7'         : 't',
'8'         : '',
'9'         : '',
'0'         : 'o',
'('         : 'c',
'[)'        : 'd',
']]='       : 'f',
',|'        : 'j',
']{'        : 'k',
'(V)'       : 'm',
'(\)'       : 'n',
'()'        : '0',
'[]D'       : 'p',
'$'         : 's',
'(_)'       : 'u',
'%'         : 'x',
'.'         : ' ',
"'"         : '',
"`"         : ''
})