# Generated by Django 3.0.4 on 2020-03-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_instagram_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowed',
            name='to_who',
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='what',
        ),
        migrations.DeleteModel(
            name='Belonging',
        ),
        migrations.DeleteModel(
            name='Borrowed',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
