# Generated by Django 3.0.4 on 2020-04-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20200310_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instagram_Comments',
            new_name='Comments',
        ),
    ]
