# Generated by Django 3.0.4 on 2020-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linq_username', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2200)),
                ('YT_username', models.CharField(max_length=100)),
                ('YT_userId', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('video_id', models.CharField(max_length=100)),
            ],
        ),
    ]
