# Generated by Django 3.0.4 on 2020-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_Id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
