# Generated by Django 3.0.4 on 2020-04-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20200409_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='YT_userId',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
